<Image_Note_Tab>:
    ScrollView:
        MDGridLayout:
            id: image_list
            cols: 2
            adaptive_height: True
            padding: dp(4), dp(4)
            spacing: dp(4)

    MDFloatingActionButtonSpeedDial:
        data: root.data
        root_button_anim: True
        callback: root.callback

<Image_list>:
    FloatLayout:
        MDIconButton:
            pos: root.x , root.y
            icon: "trash-can"
            on_press: root.remove_image(root)